### ISSUE TITLE
Do you have benchmarks available?

### ISSUE THREAD

**Issue by SteveBronder** [mitsuba-renderer/enoki#29]
I really like your design! Do you have any benchmarks available for example problems like the graphs in Figure 8 of the Stan math paper?

https://arxiv.org/pdf/1509.07164.pdf

**Comment by wjakob** [comment]
Not currently, any help in this regard would be appreciated. Note that Enoki is not going to be particularly performant for matrix multiplication (the Fig 8 example), since that is not something that it is specifically designed to do well. I'll close this ticket since it is not really an issue with the library but rather a wish.
