### ISSUE TITLE
Specifying array sizes for CUDAArray template.

### ISSUE THREAD

**Issue by stolk** [mitsuba-renderer/enoki#89]
First off, thank you for sharing enoki!

I've transformed an existing avx intrinsics code to enoki, by using `enoki::Array<float,8>` instead of `__m256` and that worked splendidly!

As the next step, I wanted to move from CPU to GPU, which should be a pretty easy chance, I sense from the docs.

As a first surprise, I noticed that I can no longer specify array sizes for the templates.

`enoki::Array<float,8>` works but `enoki::CUDAArray<float,256>` does not.

Is this by design? What is the rationale for the difference in the APIs? Should all types of CUDAArrays be of unspecified size?

The documentation does not seem to address this?

**Comment by wjakob** [comment]
There are static compile-time arrays and dynamic one. CUDAArray is dynamic, so it can deal with any given size. For the GPU to make any sense at all, you'll want a few 100Ks of entries so that the computation can be spread out over the whole chip. You would usually start with `linspace` or `full` or `empty` or `zero` or `arange` which all take an optional size argument and then do things with the result (which will also have the same size.). Operations involving arrays of size `1` and size `n>1` are also legal and will involve broadcasting, this is an important optimization.

**Comment by wjakob** [comment]
I suggest that you start playing with the Python bindings to get a feeling for how it works before using the C++ interface.

**Comment by stolk** [comment]
@wjakob Thanks! I moved to millions of entries. But my output is also millions of entries. The examples like pi-estimate just create a very small result. But how would I get an array back to the host? There is no ::store() and ::map() doesn't seem to work? I tied indexing with [ ] reading one at a time, but that is so slow, it never completes.
```
cuda_eval(): launching kernel (n=16777216, in=0, out=3, ops=92)

  ID        Type   E/I Refs   Size        Memory     Ready    Label
  =================================================================
  102       f32    1 / 0      16777216    64 MiB      [x]     
  103       f32    1 / 0      16777216    64 MiB      [x]     
  104       f32    1 / 0      16777216    64 MiB      [x]     
  =================================================================

  Memory usage (ready)     : 192 MiB
  Memory usage (scheduled) : 192 MiB + 0 B = 192 MiB
  Memory savings           : 0 B

  cuda_malloc() usage: 192 MiB device, 0 B managed, 0 B host.
           max. usage: 192 MiB device, 0 B managed, 0 B host.

```
